modLoader="javafml"
loaderVersion="[40,)"
license="LGPLv3"
issueTrackerURL="https://github.com/yungnickyoung/Ribbits/issues"

[[mods]]
    modId="${mod_id}"
    version="${version}"
    displayName="${mod_full_name}"
    credits="Thank you to the community for all your great ideas!"
    authors="Joosh, YUNGNICKYOUNG, HellionGames"
    description="${mod_description}"
    logoFile="icon.png"
    displayURL="https://www.curseforge.com/minecraft/mc-mods/ribbits"

[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"

[[dependencies.${mod_id}]]
    modId="forge"
    mandatory=true
    versionRange="[40.1.0,)"

[[dependencies.${mod_id}]]
    modId="yungsapi"
    versionRange="[${mc_version}-Forge-${yungsapi_version},)"
    mandatory=true
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="geckolib3"
    versionRange="[${forge_geckolib_version},)"
    mandatory=true
    ordering="NONE"
    side="BOTH"