modLoader="javafml"
loaderVersion="[40,)"
license="LGPLv3"
issueTrackerURL="https://github.com/yungnickyoung/Ribbits/issues"

[[mods]]
    modId="ribbits"
    version="${file.jarVersion}"
    displayName="Ribbits"
    credits="Thank you to the community for all your great ideas!"
    authors="Joosh, YUNGNICKYOUNG, HellionGames"
    description="Adds cute lil froggy bois to swamps!"
    logoFile="icon.png"
    displayURL="https://www.curseforge.com/minecraft/mc-mods/ribbits-forge"

[[dependencies.ribbits]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"

[[dependencies.ribbits]]
    modId="forge"
    mandatory=true
    versionRange="[40.1.0,)"

[[dependencies.ribbits]]
    modId="yungsapi"
    versionRange="[1.18.2-Forge-2.0.8,)"
    mandatory=true
    ordering="NONE"
    side="BOTH"